######################################################################
#
# File name : cpu_test_wave.do
# Created on: Sat May 15 00:58:43 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
