######################################################################
#
# File name : cpu_test_simulate.do
# Created on: Mon May 24 16:28:42 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xpm -L dist_mem_gen_v8_0_13 -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.cpu_test xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {cpu_test_wave.do}

view wave
view structure
view signals

do {cpu_test.udo}

run 1000ns
