# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/document/semester6/ComputerSystemExperiment/Wishbone/Wishbone.srcs/sources_1/ip/sd_buf/sd_buf.xci
# IP: The module: 'sd_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/document/semester6/ComputerSystemExperiment/Wishbone/Wishbone.gen/sources_1/ip/sd_buf/sd_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sd_buf'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: G:/document/semester6/ComputerSystemExperiment/Wishbone/Wishbone.srcs/sources_1/ip/sd_buf/sd_buf.xci
# IP: The module: 'sd_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/document/semester6/ComputerSystemExperiment/Wishbone/Wishbone.gen/sources_1/ip/sd_buf/sd_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sd_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
