# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/document/semester6/ComputerSystemExperiment/Wishbone/Wishbone.srcs/sources_1/ip/clk_wiz_200MHZ/clk_wiz_200MHZ.xci
# IP: The module: 'clk_wiz_200MHZ' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/document/semester6/ComputerSystemExperiment/Wishbone/Wishbone.gen/sources_1/ip/clk_wiz_200MHZ/clk_wiz_200MHZ_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_200MHZ'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/document/semester6/ComputerSystemExperiment/Wishbone/Wishbone.gen/sources_1/ip/clk_wiz_200MHZ/clk_wiz_200MHZ.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_200MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/document/semester6/ComputerSystemExperiment/Wishbone/Wishbone.gen/sources_1/ip/clk_wiz_200MHZ/clk_wiz_200MHZ_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_200MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: G:/document/semester6/ComputerSystemExperiment/Wishbone/Wishbone.srcs/sources_1/ip/clk_wiz_200MHZ/clk_wiz_200MHZ.xci
# IP: The module: 'clk_wiz_200MHZ' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/document/semester6/ComputerSystemExperiment/Wishbone/Wishbone.gen/sources_1/ip/clk_wiz_200MHZ/clk_wiz_200MHZ_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_200MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/document/semester6/ComputerSystemExperiment/Wishbone/Wishbone.gen/sources_1/ip/clk_wiz_200MHZ/clk_wiz_200MHZ.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_200MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: g:/document/semester6/ComputerSystemExperiment/Wishbone/Wishbone.gen/sources_1/ip/clk_wiz_200MHZ/clk_wiz_200MHZ_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_200MHZ'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
